// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKrxHhM03aSGeWJu7g7K0z8mzj507SKK8',
    appId: '1:784809884242:web:411cba8f54e43f9c63bd8b',
    messagingSenderId: '784809884242',
    projectId: 'sudarma-apparel',
    authDomain: 'sudarma-apparel.firebaseapp.com',
    storageBucket: 'sudarma-apparel.firebasestorage.app',
    measurementId: 'G-GNG4ZJ5ZKB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHW-SzLIOEUzTxjEGUHey17TXJlWF7yUU',
    appId: '1:784809884242:android:9728ac058b00e22563bd8b',
    messagingSenderId: '784809884242',
    projectId: 'sudarma-apparel',
    storageBucket: 'sudarma-apparel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgcX9hVeq4AxIY4dfbsoE6yEnCCaCmlDc',
    appId: '1:784809884242:ios:585665f74352eb6d63bd8b',
    messagingSenderId: '784809884242',
    projectId: 'sudarma-apparel',
    storageBucket: 'sudarma-apparel.firebasestorage.app',
    iosBundleId: 'com.example.expense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgcX9hVeq4AxIY4dfbsoE6yEnCCaCmlDc',
    appId: '1:784809884242:ios:585665f74352eb6d63bd8b',
    messagingSenderId: '784809884242',
    projectId: 'sudarma-apparel',
    storageBucket: 'sudarma-apparel.firebasestorage.app',
    iosBundleId: 'com.example.expense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKrxHhM03aSGeWJu7g7K0z8mzj507SKK8',
    appId: '1:784809884242:web:990fed04fdc7e76763bd8b',
    messagingSenderId: '784809884242',
    projectId: 'sudarma-apparel',
    authDomain: 'sudarma-apparel.firebaseapp.com',
    storageBucket: 'sudarma-apparel.firebasestorage.app',
    measurementId: 'G-MHNTDG8MX7',
  );

}