// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMBMW9-bxwoof87cO5LxP3h1J7nm54aL0',
    appId: '1:539527307364:web:9f500cb860a8de7f75bf71',
    messagingSenderId: '539527307364',
    projectId: 'sudarma-apparel-stock-managing',
    authDomain: 'sudarma-apparel-stock-managing.firebaseapp.com',
    storageBucket: 'sudarma-apparel-stock-managing.firebasestorage.app',
    measurementId: 'G-MKL59E817J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiMb9BjxFqvojhsTowSO8JWKWYmYjAuxk',
    appId: '1:539527307364:android:d954a8721ed5bd0b75bf71',
    messagingSenderId: '539527307364',
    projectId: 'sudarma-apparel-stock-managing',
    storageBucket: 'sudarma-apparel-stock-managing.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRgqkuWJItLE940uavERVlU2c8SGdMDEc',
    appId: '1:539527307364:ios:177930c00ba9b20075bf71',
    messagingSenderId: '539527307364',
    projectId: 'sudarma-apparel-stock-managing',
    storageBucket: 'sudarma-apparel-stock-managing.firebasestorage.app',
    iosBundleId: 'com.example.expense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRgqkuWJItLE940uavERVlU2c8SGdMDEc',
    appId: '1:539527307364:ios:177930c00ba9b20075bf71',
    messagingSenderId: '539527307364',
    projectId: 'sudarma-apparel-stock-managing',
    storageBucket: 'sudarma-apparel-stock-managing.firebasestorage.app',
    iosBundleId: 'com.example.expense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMBMW9-bxwoof87cO5LxP3h1J7nm54aL0',
    appId: '1:539527307364:web:59ba1c2e8cfa21d975bf71',
    messagingSenderId: '539527307364',
    projectId: 'sudarma-apparel-stock-managing',
    authDomain: 'sudarma-apparel-stock-managing.firebaseapp.com',
    storageBucket: 'sudarma-apparel-stock-managing.firebasestorage.app',
    measurementId: 'G-018KCF8E3C',
  );
}
